os: linux
dist: focal
language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    update: true
    packages:
      - libboost-all-dev
      - libtbb-dev
install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  - travis_retry wget --no-check-certificate https://cmake.org/files/v3.22/cmake-3.22.5-linux-x86_64.tar.gz
  - tar -xvf cmake-3.22.5-linux-x86_64.tar.gz > /dev/null
  - mv cmake-3.22.5-linux-x86_64 cmake-install
  - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
  - cd ${DEPS_DIR}
  - sudo apt remove --purge python
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda env update --file ${TRAVIS_BUILD_DIR}/test/pytest/environment.yml --name base
  - cd ${TRAVIS_BUILD_DIR}
script:
  - cmake --version
  - mkdir build
  - cd build
  - export BOOST_ROOT=/usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0
  - export Python_ROOT_DIR=$HOME/miniconda
  - cmake .. -DBUILD_TESTS=ON -DBUILD_MULTIPLE_TEST=ON -DBUILD_EXAMPLE_GAUSS_NEWTON_NLLS=ON -DBUILD_EXAMPLE_README=ON
  - cmake --build . --config Release --target NumCppPy -- -j8
  - cmake --build . --config Release --target Multiple -- -j8
  - cmake --build . --config Release --target GaussNewtonNlls -- -j8
  - cmake --build . --config Release --target ReadMe -- -j8
  - sudo make install
  - cd ../test/pytest
  - $HOME/miniconda/bin/python -m pytest
